#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

if ! command -v docker >/dev/null 2>&1; then
  echo "Ошибка: Docker не установлен. Установите Docker Engine и Docker Compose Plugin." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Ошибка: Docker Compose Plugin не найден." >&2
  exit 1
fi

if [[ -f .env ]]; then
  read -r -p ".env уже существует. Перезаписать его? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Установка отменена."
    exit 0
  fi
fi

read -r -p "Email администратора: " admin_email
if [[ ! "$admin_email" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]]; then
  echo "Ошибка: введён некорректный email." >&2
  exit 1
fi

read -r -p "Публичный адрес MinIO [localhost]: " minio_public_endpoint
minio_public_endpoint="${minio_public_endpoint:-localhost}"

random_hex() {
  openssl rand -hex "$1"
}

if ! command -v openssl >/dev/null 2>&1; then
  echo "Ошибка: openssl не установлен." >&2
  exit 1
fi

postgres_user="feed_$(random_hex 6)"
postgres_password="$(random_hex 32)"
minio_root_user="minio$(random_hex 6)"
minio_root_password="$(random_hex 32)"
jwt_secret="$(random_hex 64)"
dataprotection_password="$(random_hex 64)"

umask 077
cat > .env <<EOF
# Generated by install.sh. Keep this file private.
POSTGRES_USER=$postgres_user
POSTGRES_PASSWORD=$postgres_password
POSTGRES_DB=feeddb

MINIO_ROOT_USER=$minio_root_user
MINIO_ROOT_PASSWORD=$minio_root_password
MINIO_BUCKET=feed-files
MINIO_PUBLIC_ENDPOINT=$minio_public_endpoint

JWT_SECRET=$jwt_secret
ADMIN_EMAIL=$admin_email
DATAPROTECTION_CERT_PASSWORD=$dataprotection_password
EOF
chmod 600 .env

echo "Конфигурация создана в .env. Запускаю production-стек..."
docker compose -f docker-compose.prod.yml up -d --build

echo
echo "Установка завершена."
echo "Проверьте статус: docker compose -f docker-compose.prod.yml ps"